weba:
  build: .
  expose:
    - 8022

webb:
  build: .
  expose:
    - 8022

webc:
  build: .
  expose:
    - 8022

haproxy:
  build: ./haproxy 
  links:
   - weba
   - webb
   - webc
  ports:
   - "8022:8022"
   - "71:70"

  expose:
   - "8022"
   - "71"

